#!/bin/sh
# SPDX-FileCopyrightText: 2026 shadPS4 Emulator Project
# SPDX-License-Identifier: GPL-2.0-or-later
#
# Regenerates src/spirv_shaders.h from the GLSL sources.
# Needs glslangValidator (and optionally spirv-val). The generated header is
# committed, so building the probe does not require either tool.

set -eu
here=$(cd "$(dirname "$0")" && pwd)
out="$here/../src/spirv_shaders.h"
tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

for name in pattern_bda pattern_ssbo; do
    glslangValidator -V --target-env vulkan1.2 --vn "${name}_spv" \
        -o "$tmp/$name.h" "$here/$name.comp" >/dev/null
    glslangValidator -V --target-env vulkan1.2 -o "$tmp/$name.spv" "$here/$name.comp" >/dev/null
    if command -v spirv-val >/dev/null 2>&1; then
        spirv-val --target-env vulkan1.2 "$tmp/$name.spv"
    fi
done

{
    echo "// SPDX-FileCopyrightText: 2026 shadPS4 Emulator Project"
    echo "// SPDX-License-Identifier: GPL-2.0-or-later"
    echo "// Generated by shaders/regen_spirv.sh. Do not edit."
    echo "#pragma once"
    echo "// clang-format off"
    echo "#include <cstdint>"
    for name in pattern_bda pattern_ssbo; do
        # glslangValidator emits "const uint32_t name[] = {...};"; make it inline.
        sed -e 's/^const uint32_t/inline constexpr uint32_t/' -e '/^[[:space:]]*\/\//d' -e '/^[[:space:]]*#pragma once/d' \
            "$tmp/$name.h"
    done
} >"$out"
echo "wrote $out"
